--BORRADO DE TABLAS
DROP TABLE RECEPCIONISTAS CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE MODALIDADES CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTISTA CASCADE CONSTRAINTS;
DROP TABLE PROOVEDORES CASCADE CONSTRAINTS;
DROP TABLE ACOPIO CASCADE CONSTRAINTS;
DROP TABLE CONTRATISTAS CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE CASCADE CONSTRAINTS;
DROP TABLE FACTURAS CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE_TRANSPORTISTA CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE_CONTRATISTA CASCADE CONSTRAINTS;




--BORRADO DE SECUENCIASS
DROP SEQUENCE SQ_PAGOS;
DROP SEQUENCE SQ_MODALIDADES;
DROP SEQUENCE SQ_ACOPIO;
DROP SEQUENCE SQ_TRANSPORTE;
DROP SEQUENCE SQ_FACTURAS;
DROP SEQUENCE SQ_TRANSPORTE_CONTRATISTA;
DROP SEQUENCE SQ_TRANSPORTE_TRANSPORTISTA;

--CREACION DE SECUENCIAS
   CREATE SEQUENCE SQ_PAGOS
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
  
     CREATE SEQUENCE SQ_TRANSPORTE_CONTRATISTA
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
  
     CREATE SEQUENCE SQ_TRANSPORTE_TRANSPORTISTA
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
  
   CREATE SEQUENCE SQ_MODALIDADES
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
  
   CREATE SEQUENCE SQ_ACOPIO
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;

 CREATE SEQUENCE SQ_TRANSPORTE
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
  
   CREATE SEQUENCE SQ_FACTURAS
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1;
--CREACION TABLAS
CREATE TABLE RECEPCIONISTAS(
rut_recepcionista VARCHAR2(10) NOT NULL,
nombre_recepcionista VARCHAR2(50) NOT NULL,
created_at date,
updated_at date,
CONSTRAINT pk_rut_recepcionista PRIMARY KEY(rut_recepcionista)
);

CREATE TABLE PAGOS(
id_pago INT NOT NULL,
descripcion_pago VARCHAR2(200),
fecha_pago VARCHAR2(50),
created_at DATE,
updated_at DATE,
CONSTRAINT pk_id_pago PRIMARY KEY(id_pago)
);

CREATE TABLE MODALIDADES(
id_modalidad INT NOT NULL,
fk_id_pago INT NOT NULL,
descripcion_modalidad VARCHAR2(200),
created_at DATE,
updated_at DATE,
CONSTRAINT pk_id_modalidad PRIMARY KEY(id_modalidad),
CONSTRAINT fk_id_pago FOREIGN KEY(fk_id_pago) REFERENCES PAGOS(id_pago)
);

CREATE TABLE TRANSPORTISTA(
rut_transportista VARCHAR2(10) NOT NULL,
nombre_transportista VARCHAR2(100),
created_at DATE,
updated_at DATE,
CONSTRAINT pk_rut_transportista PRIMARY KEY(rut_transportista)
);

CREATE TABLE PROOVEDORES(
rut_proovedor VARCHAR2(10) NOT NULL,
nombre_proovedor VARCHAR2(20),
created_at DATE,
updated_at DATE,
CONSTRAINT pk_rut_proovedor PRIMARY KEY(rut_proovedor)
);

CREATE TABLE CONTRATISTAS(
rut_contratista VARCHAR2(10) NOT NULL,
nombre_contratista VARCHAR2(50),
created_at DATE,
updated_at DATE,
CONSTRAINT pk_rut_contratista PRIMARY KEY(rut_contratista)
);

CREATE TABLE TRANSPORTE(
id_transporte INT NOT NULL,
patente VARCHAR2(10),
largo_camion FLOAT,
created_at DATE,
updated_at DATE,
CONSTRAINT pk_id_transporte PRIMARY KEY(id_transporte)
);
CREATE TABLE TRANSPORTE_CONTRATISTA(
id_transporte_contratista INT NOT NULL,
fk_rut_contratista VARCHAR2(10),
fk_id_transporte INT NOT NULL,
 CONSTRAINT fk_id_transporte FOREIGN KEY(fk_id_transporte)
 REFERENCES TRANSPORTE(id_transporte),
 CONSTRAINT fk_rut_contratista FOREIGN KEY(fk_rut_contratista)
 REFERENCES CONTRATISTAS(rut_contratista)
);
CREATE TABLE TRANSPORTE_TRANSPORTISTA(
id_transporte_transportista INT NOT NULL,
fkK_id_transporte INT NOT NULL,
fkK_rut_transportista VARCHAR2(10) NOT NULL,
 CONSTRAINT fkK_id_transporte FOREIGN KEY(fkK_id_transporte)
 REFERENCES TRANSPORTE(id_transporte),
 CONSTRAINT fkK_rut_transportista FOREIGN KEY(fkK_rut_transportista)
 REFERENCES TRANSPORTISTA(rut_transportista)
);

CREATE TABLE ACOPIO(
id_acopio INT NOT NULL,
fk_rut_proveedor VARCHAR2(10) NOT NULL,
fk2_id_transporte INT NOT NULL,
nombre_acopio VARCHAR2(50),
capacidad FLOAT,
lugar_acopio VARCHAR2(50),
metros_ruma FLOAT,
calidad VARCHAR2(50),
created_at DATE,
updated_at DATE,
CONSTRAINT fk2_id_transporte FOREIGN KEY(fk2_id_transporte)
REFERENCES TRANSPORTE(id_transporte),
CONSTRAINT pk_id_acopio PRIMARY KEY(id_acopio),
CONSTRAINT fk_rut_proveedor FOREIGN KEY (fk_rut_proveedor)
REFERENCES PROOVEDORES(rut_proovedor)

);


CREATE TABLE FACTURAS(
id_factura INT NOT NULL,
fk_id_modalidad INT NOT NULL,
fk_rut_recepcionista VARCHAR2(10) NOT NULL,
calculo_madera FLOAT,
recepcion INT,
fecha_factura DATE,
num_faena INT,
altura_uno FLOAT,
altura_dos FLOAT,
altura_tres FLOAT,
altura_cuatro FLOAT,
created_at DATE,
updated_at DATE,
CONSTRAINT pk_id_factura PRIMARY KEY(id_factura),
CONSTRAINT fk_id_modalidad FOREIGN KEY(fk_id_modalidad) REFERENCES MODALIDADES(id_modalidad),
CONSTRAINT fk_rut_recepcionista FOREIGN KEY(fk_rut_recepcionista) REFERENCES RECEPCIONISTAS(rut_recepcionista)
);
--POBLADO DE TABLAS
INSERT INTO PAGOS VALUES(SQ_PAGOS.NEXTVAL,'efectivo mensual',31/10/2020,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PAGOS VALUES(SQ_PAGOS.NEXTVAL,'efectivo anual',24/09/2018,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO TRANSPORTISTA VALUES('17736253-9','Pedro Paramo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TRANSPORTISTA VALUES('19283465-1','Claudia Figueroa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO CONTRATISTAS VALUES('19836284-K','Futuro ltda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO CONTRATISTAS VALUES('16523584-3','Hermanos Soto',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO PROOVEDORES VALUES('17274612-0','Asociacion Fuentes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PROOVEDORES VALUES('12435267-6','Triagro',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO MODALIDADES VALUES(SQ_MODALIDADES.NEXTVAL,1,'6 cuotas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO MODALIDADES VALUES(SQ_MODALIDADES.NEXTVAL,2,'5 cuotas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO RECEPCIONISTAS VALUES('18396263-9','Miguel herrera',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO RECEPCIONISTAS VALUES('18363627-6','Luis Ulloa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO TRANSPORTE VALUES(SQ_TRANSPORTE.NEXTVAL,'AJSG2938',2.15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TRANSPORTE VALUES(SQ_TRANSPORTE.NEXTVAL,'akjo1637',3.0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO ACOPIO VALUES(SQ_ACOPIO.NEXTVAL,'17274612-0',2,'BOSQUE NATIVO',25.4,'SANTIAGO',13.5,'BUENA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO ACOPIO VALUES(SQ_ACOPIO.NEXTVAL,'12435267-6',2,'BOSQUE NATIVO',25.4,'SANTIAGO',13.5,'BUENA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO TRANSPORTE_TRANSPORTISTA VALUES(SQ_TRANSPORTE_TRANSPORTISTA.NEXTVAL,2,'17736253-9');
INSERT INTO TRANSPORTE_TRANSPORTISTA VALUES(SQ_TRANSPORTE_TRANSPORTISTA.NEXTVAL,1,'19283465-1');

INSERT INTO TRANSPORTE_CONTRATISTA VALUES(SQ_TRANSPORTE_CONTRATISTA.NEXTVAL,'19836284-K',1);
INSERT INTO TRANSPORTE_CONTRATISTA VALUES(SQ_TRANSPORTE_CONTRATISTA.NEXTVAL,'16523584-3',2);

INSERT INTO FACTURAS VALUES(SQ_FACTURAS.NEXTVAL,1,'18396263-9',30.1,1,CURRENT_TIMESTAMP,1,12.1,13.2,12.3,15.4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO FACTURAS VALUES(SQ_FACTURAS.NEXTVAL,1,'18363627-6',30.1,1,'04/06/2015',1,12.1,13.2,12.3,15.4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

--UPDATES
UPDATE TRANSPORTE
SET patente = 'AJSG5827'
WHERE id_transporte = 1;

UPDATE RECEPCIONISTAS
SET nombre_recepcionista = 'LUISA'
WHERE nombre_recepcionista = 'Luis Ulloa';

UPDATE PROOVEDORES
SET UPDATED_AT = CURRENT_TIMESTAMP
WHERE nombre_proovedor= 'Triagro' ;
